config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :parks, only: [:index, :show]

  namespace :charts do
    get "total-visits"
    get "park-annual-visitors"
    get "acerage-by-park"
    get "visitors-by-park"
    get "parks-per-state"
  end

  get "about", to: "pages#about"
end

app/models/annual_visitor_total.rb
class AnnualVisitorTotal < ActiveRecord::Base
  validates :year, presence: true
  belongs_to :park
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad.rb
# frozen_string_literal: true

# this is an example of code that will fail for a HoundCI demonstration
class Bad
  def initialize
    'really long string reallyreally long string reallyreally long string reallyreally long string reallyreally long string really'
  end
end

app/models/chart.rb
class Chart
  def self.width(device)
    if device == "mobile"
      "300px"
    else
      "600px"
    end
  end
end

app/models/park.rb
class Park < ActiveRecord::Base
  validates :name, presence: true
  has_many :annual_visitor_totals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :device_type

  def device_type
    if browser.mobile?
      "mobile"
    elsif browser.tablet?
      "tablet"
    else
      "desktop"
    end
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def total_visits
    year_range = 1985..2016
    totals_by_year = {}

    year_range.each do |year|
      yearly_totals_array = AnnualVisitorTotal.where(year: Date.new(year)).pluck(:visitors)
      totals_by_year[year] = yearly_totals_array.reduce(:+)
    end

    render json: totals_by_year.to_json
  end

  def park_annual_visitors
    park = Park.find(params[:id])
    park_data = park.annual_visitor_totals.pluck(:year, :visitors)

    render json: park_data.to_json
  end

  def acerage_by_park
    parks_with_acreage = Park.all.pluck(:name, :acres)

    render json: parks_with_acreage
  end

  def visitors_by_park
    total_visitors_by_park = {}

    Park.all.each do |park|
      visitors = park.annual_visitor_totals.pluck(:visitors).reduce(:+)
      total_visitors_by_park[park.name] = visitors
    end

    render json: total_visitors_by_park.sort.to_json
  end

  def parks_per_state
    parks_per_state = {}

    Park.all.each do |park|
      if park.states.include?('&')
        park.states.split(' & ').each do |state|
          if parks_per_state[state]
            parks_per_state[state] += 1
          else
            parks_per_state[state] = 1
          end
        end
      elsif parks_per_state[park.states]
        parks_per_state[park.states] += 1
      else
        parks_per_state[park.states] = 1
      end
    end

    render json: parks_per_state.to_json
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
    @acres = Park.all.pluck(:acres).reduce(:+).round(2)
    @visitors = AnnualVisitorTotal.where(year: Date.new(2016)).pluck(:visitors).reduce(:+)
  end

  def about
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # @acres = Park.all.pluck(:acres).reduce(:+).round(2)
    @visitors = AnnualVisitorTotal.where(year: Date.new(2016)).pluck(:visitors).reduce(:+)
  end

  def about
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
    @visitor_totals = AnnualVisitorTotal.where(park_id: @park.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hero_image_name(park)
    if park.nil?
      "hero.png"
    else
      "hero/#{park.name.downcase.gsub(' ', '_')}_hero.jpg"
    end
  end
end

app/views/homes/home.html.erb
<div class="hp__wrapper">

  <div class="card">
    <div class="quote">
      <h2>"We are prone to speak of the resources of this country as inexhaustible; this is not so."</h2>
      <h4>- Theodore Roosevelt</h4>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart">
      <div class="chart__geo">
        <%= geo_chart charts_parks_per_state_path, width: "600px", height: "300px", colors: "#355e3b", library: {region: 'US', resolution: 'provinces'}, key: ENV['GOOGLE_API_KEY'] %>
      </div>
    </div>

    <div class="intro">
      <div class="intro__text">
        <p>
          There are 59 National Parks in the United States. Each of them offers unparalleled, pristine beauty preserved for the benefit of all. From the Yosemite Valley in California to Cadillac Mountain in Maine, each park has a story to tell.
        </p>
      </div>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart">
      <div class="chart__line">
        <%= line_chart charts_total_visits_path, width: "600px", height: "300px", xtitle: "Year", ytitle: "Total Visitors", library: { baseline: 2000 } %>
      </div>
    </div>

    <div class="intro">
      <div class="intro__text">
        <p>
          In 2016, the National Parks Service centennial, over 82 million people visited the National Parks.  Thats one out of every four people in the United States.
        </p>
      </div>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart__group">
      <div class="chart__callout">
        <h2><%= number_with_delimiter(@acres, delimiter: ',') %><span> ACRES</span></h2>
        <h2><span>IN</span> 59 <span>PARKS</span></h2>
      </div>
      <div class="chart__pie">
        <%= pie_chart charts_acerage_by_park_path, legend: false, colors: ["#000050", "#191961", "#323272", "#4c4c84", "#666696", "#7f7fa7", "#9999b9", "#b2b2ca", "#ccccdc", "#e5e5ed"], donut: true, width: "400px", height: "400px;" %>
      </div>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart__group">
      <div class="chart__pie">
        <%= pie_chart charts_visitors_by_park_path, legend: false, colors: ["#355e3b", "#496e4e", "#5d7e62", "#718e75", "#859e89", "#9aae9d", "#aebeb0", "#c2cec4", "#d6ded7", "#eaeeeb"], donut: true, width: "400px", height: "400px;" %>
      </div>
      <div class="chart__callout">
        <h2><%= number_with_delimiter(@visitors, delimiter: ',') %><span> VISITORS</span></h2>
        <h2><span>IN</span> 2016</h2>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Congaree</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald:300,400,600" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="app__wrapper">
      <nav>
        <div class="nav__wrapper">
          <div class="nav__wrapper-content">
            <ul>
              <li class="left"><a href="<%= root_path %>"><%= image_tag("compass.png", alt: "compass arrow", class: "compass-arrow-logo") %>PR</a></li>
              <li><a href="<%= parks_path %>">Parks |</a></li>
              <li><a href="<%= about_path %>">About</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="header__wrapper">
          <% if @park&.photo || params[:id].nil? %>
            <%= image_tag(hero_image_name(@park), alt: "park image", class: "hero-image") %>
          <% else %>
            <div class="hero-image-mock">
            </div>
          <% end %>
        <div class="header__text">
          <% if @park %>
            <h1 class="page-title"><%= @park.name %></h1>
            <h3 class="page-subtitle"><%= "#{@park.states}, #{number_with_delimiter(@park.acres, delimiter: ',')} acres" %></h3>
            <h3 class="page-subtitle-est"><%= "est. #{@park.est&.strftime('%Y')}"%></h3>
          <% else %>
            <h1 class="page-title">Parks</h1>
            <h1 class="page-title">Report</h1>
          <% end %>
          <%#= image_tag("compass.png", alt: "compass arrow", class: "compass-arrow") %>
        </div>
      </div>
      <main class="app__main">
        <%= yield %>
      </main>
    </div>
    <div class="app__footer">
      <div class="app__footer-logo">
        <a href="<%= root_path %>"><%= image_tag("compass.png", alt: "compass arrow", class: "compass-arrow-logo") %>PR</a>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="card">
  <div class="intro">
    <div class="intro__text">
      <p>
        Parks Report is an attempt to take National Park data and present it in a way that illustrates the importance of our National Parks.  At a time when our nation's limited resources are under attack, we <strong>must</strong> come together to protect them.  Our parks are a vision of democracy at its best; set aside for every person of every means to enjoy.
      </p>

      <p>
        There are several resources available to learn more about our parks:
      </p>
      <div class="learn-more-list">
        <ul>
          <li><a href="https://www.nps.gov">National Park Service</a></li>
          <li><a href="https://www.nationalparks.org">National Park Foundation</a></li>
          <li><a href="https://www.npca.org">National Park Conservation Association</a></li>
          <li><a href="http://www.sierraclub.org/">Sierra Club</a></li>
        </ul>
      </div>

    </div>
  </div>
  <div class="data-source">
    <p>
      Parks Report was compiled through data available on <a href="https://irma.nps.gov/Stats/">IRMA</a>
      and the <a href="https://developer.nps.gov/api/index.htm">National Park Service API</a>.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hp__wrapper">

  <div class="card">
    <div class="quote">
      <h2>"We are prone to speak of the resources of this country as inexhaustible; this is not so."</h2>
      <h4>- Theodore Roosevelt</h4>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart">
      <div class="chart__geo">
        <%= geo_chart charts_parks_per_state_path, width: "#{Chart.width(device_type)}", height: "300px", colors: "#355e3b", library: {region: 'US', resolution: 'provinces'}, key: ENV['GOOGLE_API_KEY'] %>
      </div>
    </div>

    <div class="intro">
      <div class="intro__text">
        <p>
          There are 59 National Parks in the United States. Each of them offers unparalleled, pristine beauty preserved for the benefit of all. From the Yosemite Valley in California to Cadillac Mountain in Maine, each park has a story to tell.
        </p>
      </div>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart">
      <div class="chart__line">
        <%= line_chart charts_total_visits_path, width: "#{Chart.width(device_type)}", height: "300px", xtitle: "Year", ytitle: "Total Visitors", library: { baseline: 2000 } %>
      </div>
    </div>

    <div class="intro">
      <div class="intro__text">
        <p>
          In 2016, the National Parks Service centennial, over 82 million people visited the National Parks.  Thats one out of every four people in the United States.
        </p>
      </div>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart__group">
      <div class="chart__callout">
        <h2><%= number_with_delimiter(@acres, delimiter: ',') %><span> ACRES</span></h2>
        <h2><span>IN</span> 59 <span>PARKS</span></h2>
      </div>
      <div class="chart__pie">
        <%= pie_chart charts_acerage_by_park_path, legend: false, colors: ["#000050", "#191961", "#323272", "#4c4c84", "#666696", "#7f7fa7", "#9999b9", "#b2b2ca", "#ccccdc", "#e5e5ed"], donut: true, width: "400px", height: "400px;" %>
      </div>
    </div>
  </div>

  <hr/>

  <div class="card">
    <div class="chart__group">
      <div class="chart__pie">
        <%= pie_chart charts_visitors_by_park_path, legend: false, colors: ["#355e3b", "#496e4e", "#5d7e62", "#718e75", "#859e89", "#9aae9d", "#aebeb0", "#c2cec4", "#d6ded7", "#eaeeeb"], donut: true, width: "400px", height: "400px;" %>
      </div>
      <div class="chart__callout">
        <h2><%= number_with_delimiter(@visitors, delimiter: ',') %><span> VISITORS</span></h2>
        <h2><span>IN</span> 2016</h2>
      </div>
    </div>
  </div>
</div>

app/views/parks/index.html.erb
<div class="index">
  <div class="index__wrapper">
    <% @parks.each do |park| %>
      <div class="index__item">
        <a href="<%= park_path(park) %>">
          <div class="index__item-photo">
            <% if park.photo %>
              <%= image_tag("square/#{park.name.downcase.gsub(' ', '_')}_square.jpg", alt: "park image", class: "square-image") %>
            <% end %>
          </div>
          <%= park.name %>
        </a>
        <p><%= park.states %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/parks/show.html.erb
<div class="park__wrapper card">
  <div class="chart">
    <div class="chart__line">
      <%= line_chart charts_park_annual_visitors_path(id: @park.id), width:  "#{Chart.width(device_type)}", height: "300px", xtitle: "Year", ytitle: "Total Visitors", library: { baseline: 2000} %>
    </div>
  </div>

  <div class="intro">
    <div class="intro__text">
      <p>
        <%= @park.description %>
        <br></br>
        <%= @park.weather_info %>
      </p>
    </div>
  </div>
</div>